apiVersion: v1
kind: Service
metadata:
  name: user-management-service
spec:
  selector:
    app: micro-services
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001  # Spécifie un port de ton choix
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-master-service
spec:
  selector:
    app: micro-services
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30002
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: micro-services
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30003
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  selector:
    app: micro-services
  ports:
    - protocol: TCP
      port: 4566
      targetPort: 4566
      nodePort: 30004
  type: NodePort
